import type { MedesignPlugin, PluginDesignSystem, ParseCtx, TokenInput, ThemeInput, FileEmit, DesignReviewRule } from '@medesign/plugin-api';

/** Tailwind review rule: generated/primitive code should bind to token roles (graph `uses` edges). */
const tokenBinding: DesignReviewRule = {
  id: 'tailwind-token-binding', category: 'tailwind', title: 'Primitives bind to token roles', severity: 'P2', target: 'uses edges present',
  check: ({ stats }) => { const uses = stats['edge:uses'] ?? 0; const prims = stats['node:primitive'] ?? 0; return { pass: prims === 0 || uses >= prims, detail: `${uses} role bindings across ${prims} primitives`, fix: 'Reference token-role Tailwind classes (bg-surface, text-accent) so primitives stay on-system.' }; },
};

/** The 7 semantic color roles surfaced as Tailwind utility suffixes (bg-/text-/border-/ring-…). */
const COLOR_SUFFIXES = ['surface-raised', 'surface', 'text-muted', 'text', 'accent-hover', 'accent', 'border'] as const;

function tokenKind(role: string): string {
  if (role.startsWith('color-')) return 'color';
  if (/^(font|text|leading|tracking)/.test(role)) return 'type';
  if (role.startsWith('space')) return 'spacing';
  if (role.startsWith('radius')) return 'radius';
  if (/^(shadow|focus)/.test(role)) return 'shadow';
  if (/^(motion|ease)/.test(role)) return 'motion';
  return 'layout';
}

/** Pull `--name: value;` declarations out of a CSS block. */
function declarations(css: string): Array<{ role: string; value: string }> {
  const out: Array<{ role: string; value: string }> = [];
  for (const m of css.matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/gi)) out.push({ role: m[1], value: m[2].trim() });
  return out;
}

/**
 * Deep Tailwind plugin (styling): the single source for the class→role map, parses tokens.css → tokens
 * + [data-theme] → themes, and GENERATES tailwind.config.js from the token contract.
 */
export const tailwindPlugin: MedesignPlugin = {
  id: 'tailwind',
  kind: 'styling',

  codegenInstructions(): string {
    return [
      'STYLING: Tailwind CSS.',
      '- Reference token ROLES only via semantic Tailwind classes (bg-surface, text-accent, border-border, rounded) — NEVER raw hex.',
      '- For tokens without a class alias, use arbitrary values bound to the var: shadow-[var(--shadow-raised)], duration-[var(--motion-fast)].',
      '- Reserve the accent for the single most important element (≤ ~2 per screen).',
    ].join('\n');
  },

  /** Utility-suffix → token role. Consumed by the graph's class→role extractor (single source of truth). */
  classRoles(): Record<string, string> {
    const map: Record<string, string> = { rounded: 'radius' };
    for (const s of COLOR_SUFFIXES) map[s] = `color-${s}`;
    return map;
  },

  /** Parse the design system's :root block (and any tailwind theme vars) into token inputs. */
  parseTokens(ctx: ParseCtx): TokenInput[] {
    const root = (ctx.tokensCss.match(/:root\s*\{([\s\S]*?)\}/)?.[1]) ?? ctx.tokensCss;
    return declarations(root).map((d) => ({ role: d.role, value: d.value, kind: tokenKind(d.role) }));
  },

  /** Parse `[data-theme="x"] { … }` override blocks into themes (populates the theming graph). */
  parseThemes(ctx: ParseCtx): ThemeInput[] {
    const out: ThemeInput[] = [];
    for (const m of ctx.tokensCss.matchAll(/\[data-theme=["']?([a-z0-9-]+)["']?\]\s*\{([\s\S]*?)\}/gi)) {
      const overrides = declarations(m[2]);
      if (overrides.length) out.push({ theme: m[1], overrides });
    }
    return out;
  },

  /** Generate tailwind.config.js from the token contract — collapses the hand-maintained configs. */
  emitConfig(ds: PluginDesignSystem): FileEmit[] {
    const colors = COLOR_SUFFIXES.filter((s) => ds.declaredTokens.includes(`color-${s}`));
    const colorEntries = colors.map((s) => `        '${s}': 'var(--color-${s})',`).join('\n');
    const content = `/** GENERATED by @medesign/plugin-tailwindcss from the active design system's token contract. */
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{ts,tsx}',
    './design-systems/**/code/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
${colorEntries}
      },
      borderRadius: { DEFAULT: 'var(--radius)' },
    },
  },
  plugins: [],
};
`;
    return [{ path: 'tailwind.config.js', content }];
  },

  doctorRules: () => [tokenBinding],
};

export default tailwindPlugin;
