/** @emdesign/backend — programmatic surface (the engine; the CLI lives in @emdesign/cli). */
export { resolveRepoPaths, readConfig, ensureDir } from './paths.js';
export type { RepoPaths, MedesignConfig } from './paths.js';
export { Store } from './state.js';
export type { StudioState, ChangeRequest, DiffResult } from './state.js';
export { createHttpBridge, startHttpBridge } from './http.js';
export { resolveDesignSystem, composePrompt, parseDeclaredTokens } from './designContext.js';
export type { DesignSystem } from './designContext.js';
export { lintComponent, lintTokenReferences, renderFindingsForAgent, countMustFix, tokenScore } from './lint/index.js';
export type { Finding, Severity } from './lint/index.js';
export { computeComposite, decideRound, selectFallbackRound, DEFAULT_WEIGHTS } from './critique/scoreboard.js';
export { scoreComponent, DEFAULT_SOURCE_FLOORS } from './critique/score.js';
export { collectScores } from './critique/collector.js';
export type { CollectOptions, CollectResult } from './critique/collector.js';
export { runVisualTest, toStoryId, resolveStoryId, toVisualScore, checkStorybookHealth } from './visualTest.js';
export { renderSnapshot } from './renderProbe.js';
export type { RenderSnapshotOutput, RenderSnapshotOptions } from './renderProbe.js';
export { captureComponent, captureWithBaseline } from './capture.js';
export { buildAndSave, loadOrBuild, overlayGenerated } from './graph.js';
export { createDesignSystem, scaffoldPrimitives, validateDesignSystem, updateDesignSystem, diffDesignSystems, compileDesignSystem, exportDesignSystem, listDesignSystems, listBases, listBaseCategories, baseDetail, basePreviewHtml, customizeDesignSystem, applyDesignSystem, manifestJson, designMdSkeleton, baseTokensCss, searchDesignSystems, importAwesomeDesign, importGitDesign, importProjectDesign, getDesignSystemInfo, getLintRules, setLintRule, applyLintPreset, LINT_RULE_PRESETS, listBlocks, scaffoldBlocks, listBlueprints, applyBlueprint } from './scaffold.js';
export type { CreateMode, CreateResult, ValidateResult, UpdateResult, DiffResult as DsDiffResult, CompileResult, TokenInfo, TokenCategory, ApplyResult, DesignSystemBase, DesignSystemSource, ManifestOpts, BaseDetail, RegistrySystem, DsInfo, BlockInfo, BlueprintInfo, ImportProjectResult } from './scaffold.js';
export { normalizeDsRef, setActiveDesignSystem } from './paths.js';
export { runtimeFor } from './runtime.js';
export { gradeDesignSystem, renderGrade } from './doctor.js';
export type { GradeReport, GradeOptions } from './doctor.js';
export { recordEvidence } from './evidence.js';
export { spatialAudit } from './spatial.js';
export type { SpatialAuditResult, SpatialFinding } from './spatial.js';
export type { DoctorReport, DoctorFinding } from '@emdesign/doctor';
export { lintRendered, mergeReports } from '@emdesign/doctor';
export { getAdapter, effectiveAdapter, availableFrameworks, availablePlugins } from './adapters/index.js';
export type { FrameworkAdapter } from './adapters/index.js';
export type { EffectiveAdapter } from './plugins/compose.js';
export type { MedesignPlugin, PluginKind } from '@emdesign/plugin-api';
export { registerPlugin, resolvePlugin } from './plugins/registry.js';
export { extractProject } from './project/extract.js';
export type { ExtractionResult, Observation, ProposedRole, Evidence, Conflict, ObservationKind, RoleSource } from './project/extract.js';
export { adoptProject } from './project/adopt.js';
export type { AdoptOptions } from './project/adopt.js';
export { buildAdoptionReport, summarizeReport } from './project/report.js';
export type { AdoptionReport, AdoptedComponent, ComponentStatus, ComponentChange, Rebind, BlockingValue, GraphEntry } from './project/report.js';
export { runAgent, resolveExecutable } from './harness/driver.js';
export { claudeAdapter } from './harness/claude.js';
export type { MinimalAgentDef } from './harness/types.js';
export { auditDesignSystem } from './audit.js';
export type { AuditReport, AuditFinding } from './audit.js';
