/** @medesign/backend — programmatic surface (the engine; the CLI lives in @medesign/cli). */
export { resolveRepoPaths, readConfig, ensureDir } from './paths.js';
export type { RepoPaths, MedesignConfig } from './paths.js';
export { Store } from './state.js';
export type { StudioState, ChangeRequest, DiffResult } from './state.js';
export { createHttpBridge, startHttpBridge } from './http.js';
export { resolveDesignSystem, composePrompt, parseDeclaredTokens } from './designContext.js';
export type { DesignSystem } from './designContext.js';
export { lintComponent, lintTokenReferences, renderFindingsForAgent, countMustFix, tokenScore } from './lint/index.js';
export type { Finding, Severity } from './lint/index.js';
export { computeComposite, decideRound, selectFallbackRound, DEFAULT_WEIGHTS } from './critique/scoreboard.js';
export { scoreComponent } from './critique/score.js';
export { runVisualTest, toStoryId } from './visualTest.js';
export { renderSnapshot } from './renderProbe.js';
export type { RenderSnapshotOutput, RenderSnapshotOptions } from './renderProbe.js';
export { captureComponent } from './capture.js';
export { buildAndSave, loadOrBuild, overlayGenerated } from './graph.js';
export { createDesignSystem, scaffoldPrimitives, validateDesignSystem, listDesignSystems, listBases, applyDesignSystem, manifestJson, designMdSkeleton, baseTokensCss } from './scaffold.js';
export type { CreateMode, CreateResult, ValidateResult, ApplyResult, DesignSystemBase, DesignSystemSource, ManifestOpts } from './scaffold.js';
export { normalizeDsRef } from './paths.js';
export { runtimeFor } from './runtime.js';
export { gradeDesignSystem, renderGrade } from './doctor.js';
export type { GradeReport } from './doctor.js';
export { recordEvidence } from './evidence.js';
export type { DoctorReport, DoctorFinding } from '@medesign/doctor';
export { lintRendered, mergeReports } from '@medesign/doctor';
export { getAdapter, effectiveAdapter, availableFrameworks, availablePlugins } from './adapters/index.js';
export type { FrameworkAdapter } from './adapters/index.js';
export type { EffectiveAdapter } from './plugins/compose.js';
export type { MedesignPlugin, PluginKind } from '@medesign/plugin-api';
export { registerPlugin, resolvePlugin } from './plugins/registry.js';
export { runAgent, resolveExecutable } from './harness/driver.js';
export { claudeAdapter } from './harness/claude.js';
export type { MinimalAgentDef } from './harness/types.js';
