/** GENERATED by @emdesign/plugin-tailwindcss from the active design system's token contract. */
/** @type {import('tailwindcss').Config} */
export default {

  darkMode: 'class',
  content: [
    './src/**/*.{ts,tsx}',
    './design-systems/**/code/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        'text': 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'accent': 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        'border': 'var(--color-border)',
        'highlight': 'var(--color-highlight)',
        'highlight-ink': 'var(--color-highlight-ink)',
        'success': 'var(--color-success)',
        'warn': 'var(--color-warn)',
        'danger': 'var(--color-danger)',
        'positive': 'var(--color-positive)',
        'negative': 'var(--color-negative)',
      },
      borderRadius: { DEFAULT: 'var(--radius)' },
    },
  },
  plugins: [],
};
